services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3070:80'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=${API_URL}
      - APP_URL=${APP_URL}

  api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      - pg_db
    ports:
      - '8080:8080'

  pg_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg_db:
