version: '3'

services:
  pg_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg_db:
